name: Rock5B ubuntu compiler

on:
  push:
    #branches: [ "2.4-evo" ]
  pull_request:
    #branches: [ "2.4-evo" ]

jobs:
  build:

    runs-on: ubuntu-22.04
  
    steps:

    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: install dependencies
      run: |
        sudo apt install -y build-essential gcc-aarch64-linux-gnu bison 
        sudo apt install -y  qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support
        sudo apt install -y debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted 
        sudo apt install -y udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 
        sudo apt install -y python-is-python3 fdisk bc
    - name: build
      run: sudo ./build.sh --board=rock5b

    - name: Pack image for Rock5B
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Rock5B"
        path: |
          *.img
          if-no-files-found: error